### ISSUE TITLE
Class restriction on Consignment that does not match the property domain

### ISSUE THREAD

**Issue by ocorcho** [silenroc1/FEDeRATED-copy#6]
The property usedTransportEquipment has domain LogisticsService. However, in the class Consignment there is a class restriction with the property usedTransportEquipment.

Given that the concepts BusinessTransaction and LogisticsService do not seem to be compatible (they may be declared as disjoint), this seems to be an error.

**Comment by GiuliaBiagioni** [comment]
Thank you for letting us know about the error. Due to the possible broad applicability of the Objectproperty 'usedTransportEquipment', we have decided to remove the domain LogisticsService from the property. Similarly, we chose to  maintain the restriction in the class 'Consignment' via the just referred property. The changes will be visible after the next update.

**Comment by ocorcho** [comment]
Checked, and in agreement with the change done.
